export const ORDER_STATUS = {
  PLACED: "PLACED",
  ACCEPTED: "ACCEPTED",
  PREPARING: "PREPARING",
  READY: "READY",
  COLLECTED: "COLLECTED",
  CANCELLED: "CANCELLED",
  REJECTED: "REJECTED"
};

export const PAYMENT_METHOD = {
  PAY_AT_CANTEEN: "PAY_AT_CANTEEN",
  ONLINE: "ONLINE"
};

export const PAYMENT_STATUS = {
  UNPAID: "UNPAID",
  PAID: "PAID"
};

